// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using newcsa.Models;

#nullable disable

namespace newcsa.Migrations
{
    [DbContext(typeof(CsaContext))]
    partial class CsaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("newcsa.Models.Meassage", b =>
                {
                    b.Property<int>("MsgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("msg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MsgId"));

                    b.Property<string>("MsgData")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Msg_Data");

                    b.Property<int?>("StdId")
                        .HasColumnType("int")
                        .HasColumnName("std_id");

                    b.HasKey("MsgId")
                        .HasName("PK__meassage__9CA9728D7CE642FC");

                    b.HasIndex("StdId");

                    b.ToTable("meassage", (string)null);
                });

            modelBuilder.Entity("newcsa.Models.Student", b =>
                {
                    b.Property<int>("StdId")
                        .HasColumnType("int")
                        .HasColumnName("std_id");

                    b.Property<string>("Branch")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("branch");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<int?>("Marks")
                        .HasColumnType("int")
                        .HasColumnName("marks");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("password");

                    b.Property<int?>("YOP")
                        .HasColumnType("int")
                        .HasColumnName("y_o_p");

                    b.HasKey("StdId")
                        .HasName("PK__student__0B0245BA35A63A60");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("newcsa.Models.Meassage", b =>
                {
                    b.HasOne("newcsa.Models.Student", "Std")
                        .WithMany("Meassages")
                        .HasForeignKey("StdId")
                        .HasConstraintName("FK__meassage__std_id__398D8EEE");

                    b.Navigation("Std");
                });

            modelBuilder.Entity("newcsa.Models.Student", b =>
                {
                    b.Navigation("Meassages");
                });
#pragma warning restore 612, 618
        }
    }
}
